[tool.poetry]
name = "client-s-banking-operations-widget"
version = "0.1.0"
description = "Виджет для работы с банковскими операциями: загрузка, фильтрация, сортировка, маскирование"
authors = ["VITAL <zinabir7@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=2.0.0"
openpyxl = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^5.0.0"
mock = "^5.1.0"
black = "^26.0.0"
flake8 = "^7.0.0"
mypy = "^1.10.0"
isort = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "client-s-banking-operations-widget"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "pandas>=2.0.0",
  "openpyxl",
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88